version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend

  backend:
    image: your-username/ps-project-backend:latest # Use the actual image name
    ports:
      - "4000:4000"
